### ISSUE TITLE
Introduction failure

### ISSUE THREAD

**Issue by ylq574787347** [everFinance/everpay-js#27]
in ./node_modules/arweave/web/common.js

>Module parse failed: Unexpected token (15:7)
>You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See >https://webpack.js.org/concepts#loaders
>| const blocks_1 = require("./blocks");
>| class Arweave {
>| >     api;
>|     wallets;
>|     transactions;

>@ ./node_modules/arweave/web/index.js 17:17-36 58:13-32
> @ ./node_modules/everpay/esm/lib/arweave.js
> @ ./node_modules/everpay/esm/lib/sign.js
> @ ./node_modules/everpay/esm/index.js
> @ ./src/main.js
> @ multi (webpack)-dev-server/client?http://192.168.100.41:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by Xaber20110202** [comment]
Please use arweave-js below vesion 1.11.9
